sudo: require
services:
  - docker

before_install:
  - docker build -t ruismagalhaes/continous-improvement-experience -f Dockerfile.dev .

script:
  - docker run -e CI=true ruismagalhaes/continous-improvement-experience npm run test

